---

- name: run the playbook tasks on the localhost configuration
  hosts: localhost
  connection: local
  become: yes
  vars:
    home_dir: ${HOME}
    packages:
    - build-essential
    - nodejs
    - golang
    - python-dev
    - libreadline-dev
    - libbz2-dev
    - libssl-dev
    - libsqlite3-dev
    - libxslt1-dev
    - libxml2-dev
    - libffi-dev

  tasks:

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"

  - name: Configuration bashrc
    blockinfile:
      path: "{{ home_dir }}/.bashrc"
      block: |
        export PATH="$HOME/.pyenv/bin:/snap/bin:$PATH"
        export EDITOR=micro
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        GIT_PROMPT_ONLY_IN_REPO=1
        source ~/.bash-git-prompt/gitprompt.sh
      backup: yes